site_name: WAX Performance/General Wiki
site_url: https://wiki.oiac.io
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
plugins:
  - search
nav:
  - Home: index.md
  - Installations: installation.md
  - Hyperion: hyperion.md
  - Atomic API: atomic-api.md
  - PostgreSQL: postgresql.md
  - Nodeos: nodeos.md
  - Ubuntu: ubuntu.md
  - Containers: containers.md
  - Monitoring (Prometheus/Grafana): monitoring.md
  - Loadtest setup using Locust: locust.md
  - HAProxy: haproxy.md
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences