site_name: WAX Performance Wiki
site_url: https://wiki.oiac.io
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
plugins:
  - search
nav:
  - Home: index.md
  - Hyperion: hyperion.md
  - Atomic API: atomic-api.md
  - PostgreSQL: postgresql.md
  - Nodeos: nodeos.md
  - Ubuntu: ubuntu.md
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences